language: r
dist: trusty
cache:
  directories:
    - $HOME/.cache
    - $HOME/R/Library
r_packages: covr
after_success:
 - R -e 'covr::codecov()'
 - Rscript inst/deploy/deploy.R
before_install:
  - source <(curl -s https://raw.githubusercontent.com/dynverse/travis_scripts/master/install_phantomjs.sh)
